{{- if .Values.wordpress.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "practica-final-k8s.fullname" . }}-wordpress
  labels:
    {{- include "practica-final-k8s.labels" . | nindent 4 }}
  {{- with .Values.wordpress.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  # <-- MEJORA: El Ingress Class Name ahora es configurable
  {{- if .Values.wordpress.ingress.ingressClassName }}
  ingressClassName: {{ .Values.wordpress.ingress.ingressClassName }}
  {{- end }}
  rules:
    # <-- CAMBIO AQUÃ: Ruta actualizada
    - host: {{ .Values.wordpress.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "practica-final-k8s.fullname" . }}
                port:
                  name: http
{{- end }}