apiVersion: v1
kind: Service
metadata:
  name: {{ include "practica-final-k8s.fullname" . }}
  labels:
    {{- include "practica-final-k8s.labels" . | nindent 4 }}
spec:
  # <-- CAMBIO AQUÃ: Rutas actualizadas
  type: {{ .Values.wordpress.service.type }}
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: wordpress
    instance: {{ .Release.Name }}